### PR TITLE
Implement Button+ V1.12 API and introduce compatibility layer

### PR DESCRIPTION
**Pull request by scspijker**
I've started to implement the V1.12 API and introducing a compatibility layer so it's easier to implement new versions.

For now this is a draft PR, so other maintainers can track progress and send early feedback.

So far I've:
- [x] Introduced Firmware version based model detection
- [x] Introduced unit tests for parsing JSON responses
- [x] Introduced a Docker Compose script for easy testing of the integration
- [x] Introduced V1.12 JSON parsing
- [x] Implemented the new interface model in the domain layer 🔨 

Thanks, and let me know if something could be better! This is my first Python code / contribution ever 💪

### CODE REVIEW

**Comment by koenhendriks** [comment]
I explicitly asked for changes between 1.12 and 1.13 before the release and to quote the creator of Button+:

> No changes in the config between 1.12 and 1.13

Do you think you can add the 1.13 as well?

**Review by koenhendriks — DISMISSED** [review]
Thanks a lot for your work on this! I hope this will help fix config changes faster in the future.

Really nice that you also added tests for this :+1:

**Comment by koenhendriks** [comment]
@scspijker Just 1 failing CI pipeline I see. Could you take a look? I'm not really sure what the CI actually tries because it was added by @bolkedebruin

**Comment by scspijker** [comment]
> @scspijker Just 1 failing CI pipeline I see. Could you take a look? I'm not really sure what the CI actually tries because it was added by @bolkedebruin

I'll take a look 👍

**Comment by scspijker** [comment]
@koenhendriks CI should be fixed, and now also runs the `pytest` automatically 💪 

Let's fix 1.13 in a new PR.

**Comment by scspijker** [comment]
@koenhendriks okay, let's try that _one more time_ (hopefully 😂 ). After doing some setup I could run the GHA's in my own repo, and the build now works there. The latest ubuntu runner image uses Python 3.10, but a minimum of 3.11 is required for Home Assistant. This is now setup in build.yaml, also caching dependencies.

**Comment by koenhendriks** [comment]
I might take a look at the settings of the repo, not sure why I should manually give permission for each CI run...

**Comment by scspijker** [comment]
> I might take a look at the settings of the repo, not sure why I should manually give permission for each CI run...

You have limited "free" minutes with open source repo's. So somebody with permissions (like CODE-OWNER) has to approve before CI runs. Else bad actors can use all your free minutes by just opening 200 PR's at once.

**Review by koenhendriks — APPROVED** [review]

**Comment by IBlackI** [comment]
Is it the plan to create a (beta) release with these changes?

**Comment by koenhendriks** [comment]
Just released v0.0.15

**Pull request merged**
