### PR TITLE
Fixed multiple devices clashing with add/remove

### PR DESCRIPTION
**Pull request by P-Storm**
Looks like fixing #31 and #36 .

Note: The brightness PR should be also be changed to reflect this approach.

The problem was that we defined a 'global' collection, and every time we tried to add those in, it would add 'all' in the global, not only the new ones.

### CODE REVIEW

**Comment by koenhendriks** [comment]
Thanks for your contribution, this PR looks good to me and I'm willing to just merge it without feature testing it myself :) I'll tag a new release ASAP after the merge.

**Comment by nvdweem** [comment]
This does not seem to fix #36.

I removed my devices, updated to 0.0.9 and re-added them:

image
All devices have the display + 2 bars. No idea why 2 Btn+ devices show 3 devices and the other shows 4.

The controls are still grouped:
image

**Comment by P-Storm** [comment]
> This does not seem to fix #36.
> 
> I removed my devices, updated to 0.0.9 and re-added them:
> 
> image All devices have the display + 2 bars. No idea why 2 Btn+ devices show 3 devices and the other shows 4.
> 
> The controls are still grouped: image

Can you give me the config json of your 3 devices? http://ip:port/config

Note: It contains your broker credentials plain text, so maybe obscure that :)

Can you also screenshot all button+ devices in the device list?

**Comment by nvdweem** [comment]
Requested files attached.

[benchmark-config.json](https://github.com/koenhendriks/ha-button-plus/files/14554687/benchmark-config.json)
[woonkamer-config.json](https://github.com/koenhendriks/ha-button-plus/files/14554688/woonkamer-config.json)
[slaapkamer-config.json](https://github.com/koenhendriks/ha-button-plus/files/14554689/slaapkamer-config.json)
ha-all-devices

**Comment by wimjanse** [comment]
Same problem. I have 2x B+ both with 3 bars.
I removed both B+'s from the integration and re-added both.
First B+ shows up completely, display and 3 bars
Second B+ shows up with the display and only 1 bar

**Pull request merged**
